name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [ '1.12', '1.13' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d

      - name: Build
        run: |
          go build .
